### ISSUE TITLE
Optimizing JS Javascript globally

### ISSUE THREAD

**Issue by dodieboy** [code-for-charity/Bulk-Contributor#1]
Hey, I will like to suggest to use includes() instate of indexOf() in your code when you are checking if the item exist. include() will be better in that case as you do not use the return int value of indexOf(), all you want is true or false which is what include() return. 
Since it return true or false, equal operator is not needed (improve performance) and it is a Boolean (1 bit) which use lesser memory compare to int which is 16 bit.

Here is a performance test that I did: https://www.measurethat.net/Benchmarks/ShowResult/215464

**Comment by ImprovedTube** [comment]
Hey @dodieboy  why close?☺

**Comment by dodieboy** [comment]
cant think of any better way to optimize the code, will reopen when I have the time to research new ways

**Comment by ImprovedTube** [comment]
Oh, I moved it to this repo because it potentially applies to all JS in every (public) project. Thus it stays worth reading. hopefully there is a lot to come in this repo. Hope you like that.

**Comment by dodieboy** [comment]
I recently found this article about 6 method to search for a string in JavaScript which include benchmark of all 6 method and I feel it will be useful to share around.

When searching from small string (around 30 characters)
![image](https://user-images.githubusercontent.com/9015764/171593876-0b4951e9-44a0-46ed-9fcd-cee130b7e9c2.png)

When searching from big string (more than 1 million characters)
![image](https://user-images.githubusercontent.com/9015764/171594195-86d2d600-be3f-4dca-85ec-0631c4db97fe.png)


https://koukia.ca/top-6-ways-to-search-for-a-string-in-javascript-and-performance-benchmarks-ce3e9b81ad31
